### ISSUE TITLE
CC: Cannot execute assembler. Status: 22

### ISSUE THREAD

**Issue by Decimation** [CE-Programming/toolchain#134]
I'm trying to compile [this](https://github.com/nathanfarlow/PineappleCAS) using CEdev 7.5. I'm trying to compile with 7.5 because on 8.2, I get this error:
`C:\CEDEV\INCLUDE\TICE.H (482,34) :      ERROR (121) Illegal declaration specifier`
`C:\CEDEV\INCLUDE\TICE.H (482,34) :      ERROR (177) Type specifier cannot have both "unsigned" and "signed"`
`make: *** [obj_calc/export.src] Error -1`

My reasoning behind trying to compile with 7.5 is because that's the version closest to when PineappleCAS was last updated.

Here is the full error message when I try to compile on 7.5:

`CC: Cannot execute assembler. Status: 22`
`make: *** [obj_calc/ast.obj] Error -1`

Everything I've tried so far has been unsuccessful.

**Comment by runer112** [comment]
Try compiling with the most recent release, please.

**Comment by Decimation** [comment]
Is 8.2 not the most recent release?

**Comment by runer112** [comment]
Sorry, it is. I misread your comment and thought you were only trying with 7.5. We're looking into the 8.2 issue, at least.

**Comment by jacobly0** [comment]
The 7.5 errors sound like you didn't completely switch versions or something.  The 8.2 errors are due to zds being bad and the `typedef ... error;` somehow clashing with an error parameter, which can be fixed by renaming one or the other.  The rest of the errors are due to `tice.h` doing bad things like defining user identifiers `t1`, `t2`, and `t3` which can be fixed by renaming something or `#undef`ing them.
