### ISSUE TITLE
Addition: Detection of both protected and unprotected programs

### ISSUE THREAD

**Issue by LAX18** [CE-Programming/toolchain#145]
Mateo mentioned that he would fix this so I am just going to put this here as a reminder because I know everyone has a lot going on.

Once again, thanks Mateo!

**Comment by runer112** [comment]
I would suggest fixing this by treating the program (5) and protected program (6) variable types as the same. This is how syscalls like `_ChkFindSym` work.

This could also be fixed by adding new forms of the variable searching functions that somehow accept multiple variable types to search. But unless there's a strong argument for needing to search for variables of the same name of multiple types other than program and protected program, this fix seems excessive.

**Comment by mateoconlechuga** [comment]
This would break programs that already scan for both. The best method is just to make a new function with variable arguments.

**Comment by mateoconlechuga** [comment]
Actually I have a better idea wait and see

**Comment by mateoconlechuga** [comment]
Closed with 37b49f9
