### ISSUE TITLE
Fileio functions

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/toolchain#151]
bool ti_Rename(char *old, char *new);
bool ti_RenameVar(char *old, char *new, uint8_t type);
void ti_GetName(char *name, ti_var_t slot);

**Comment by runer112** [comment]
I'd suggest considering making ti_GetName require being passed the output buffer. I've heard it's all to common (especially from ICE) that users don't realize that calling functions like this that return a string for a second time overwrites the output from the previous call, because the buffer allocation (or lack thereof) is done behind the scenes.

**Comment by mateoconlechuga** [comment]
ti_GetName is complete and tested. I'm not sure about the worth of rename functions, so may as well just leave this issue open in case someone wants them; but for now probably not.

**Comment by mateoconlechuga** [comment]
Closed with cdf513b
