### ISSUE TITLE
Double & float problem?

### ISSUE THREAD

**Issue by mattmatt0** [CE-Programming/toolchain#169]
This is supposed to dram mandelbrot set,

```
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <tice.h>


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void main(void) {
    uint32_t *lcd_Ram_i, *lcd_Ram_end = (uint32_t *) ((int) lcd_Ram + LCD_SIZE);
	uint32_t a, x, y;
        uint8_t iter;
	double c_x, c_y, z_x, z_y,oldzx,esc;
	a = 0;
	for(lcd_Ram_i = (uint32_t *) lcd_Ram; lcd_Ram_i < lcd_Ram_end; lcd_Ram_i++) 
	{
		x = a%160;
		y = (int)(a-(a % 160))/160;
                /* x, y are x y coords on screen */
		c_x = (x - 80)/10;
		c_y = (y - 120)/10;
		z_x = c_x;
		z_y = c_y;
		iter = 0;

		while(true)
		{
			oldzx = z_x;
			z_x = z_x*z_x - z_y*z_y + c_x;
			z_y = oldzx*z_y*2 + c_y;
			
			if(iter >= 5)
			{
				*lcd_Ram_i = 0;
				break;
			}
			if((z_x*z_x + z_y*z_y ) > 4)
			{
				*lcd_Ram_i = (iter+1)*1000;
				break;
			}
			iter++;
		}
		
		a++;
    }

	while (!os_GetCSC());
}
```
No compiling problem, but I get a weird rectangle, like if doubles wasn't supported, or with a very bad precision. 

PS: Sorry if my english is gramatically incorrect, I'm not english :)

**Comment by jacobly0** [comment]
The ZDS C compiler compiles all doubles as floats, and the float support code is not the best.  However, this isn't going to cause any problems at this zoom level.  The reason it is so blocky is because the expressions `(x - 80)/10` and `(y - 120)/10` only involves integers, and are therefore computed with integer math.  This means that `c_x` and `c_y` are always integers, which are not very interesting points in the mandelbrot set.
