### ISSUE TITLE
Feature Request (graphx): gfx_CompressedTransparentSprite(), gfx_RLETCompressedSprite()

### ISSUE THREAD

**Issue by acagliano** [CE-Programming/toolchain#227]
Add:
gfx_CompressedSprite()
gfx_CompressedTransparentSprite()
gfx_CompressedRLETSprite()

Similar to the normal gfx_Sprite, TransparentSprite, and RLETSprite functions, except these take pointers to *compressed* sprites, decompress them on the fly, and then render them.

To increase the speed, perhaps have the function smartly decompress the sprite to a temporary buffer the first time it needs to render a sprite and save *that* pointer to some form of database. Subsequent calls to the rendering function will check the database first, and if the sprite has already been decompressed will simply render from the decompressed buffer, only decompressing if the sprite has not already been decompressed.

To save memory, perhaps an added: gfx_MemRecover(time) function that processes the database, freeing any buffer that has not been used in 'time' time.

**Comment by runer112** [comment]
No. </mateo>

But in all seriousness, this sounds beyond the scope of what's really just a basic graphics drawing library. Something like this should just be implemented directly in your program, where you can customize everything like where the cache is, how big it is, what the eviction policy is, etc. It would also probably be much easier to write in a higher-level language than assembly, and not even much less efficient, because managing a cache of large objects isn't really a case where hand-written assembly can dramatically outperform compiled code.
