### ISSUE TITLE
Suddenly Not Working (STILL!)

### ISSUE THREAD

**Issue by DeathDragon7050** [CE-Programming/toolchain#239]
Thanks for shutting down my last issue. I still get all the errors I previously did.

**Comment by adriweb** [comment]
Dude, you can still reply in the other one while not making a new one.
The issues are caused by your code (jacobly listed all the errors), not by the toolchain, hence the issue getting closed. Doesn't mean you can't continue the discussion there if you can't figure out how to fix them from the error log (several missing colons etc., seems easy to fix)
