### ISSUE TITLE
Clipping is broken

### ISSUE THREAD

**Issue by jacobly0** [CE-Programming/toolchain#24]
One comment says the clip region is inclusive, however the default clip region (0, 0, lcdWidth, lcdHeight) is exclusive.

**Comment by adriweb** [comment]
As said on IRC, since the current function relies on a pair of points instead of point + w/h, a solution to this is to introduce: `void gfx_SetClipRect(int xmin, int ymin, unsigned int width, unsigned int height);` as we cannot break compatibility with older versions.  
(However, should the default clipping window be fixed to be `(0, 0, 319, 239)`?

**Comment by MateoConLechuga** [comment]
Or just make things exclusive. This is really only broken for lines at the moment, and it doesn't really have an affect on output.

**Comment by MateoConLechuga** [comment]
Partially fixed and tested with 7d3e9d7, need to run a few more tests though

**Comment by MateoConLechuga** [comment]
Good to go :)
