### ISSUE TITLE
Toolchain Chromebook Linux Beta Issues

### ISSUE THREAD

**Issue by Overload02** [CE-Programming/toolchain#252]
* Arm64 Linux without Intel processer does not allow toolchain to work because wine is missing wine32. wine32 can only be downloaded on the intel processer Chromebooks. aside from everything the make command works. but since wine does not work this means assembler does not work since it a .exe file. correct me if am wrong 😭

with the recent release of Ti-Connect on Chromebooks. I think the toolchain should find a way to move Chromebooks.

 Also, I think you should dummy down the Linux installation for new users to Linux 👀. 

regards, overload02

**Comment by adriweb** [comment]
Since you can't really do whatever you want on chromebooks unless you "root" them, it's not happening.
Plus, yes, as you said, Zilog tools are windows only and thus require wine on non-Windows, which is what the current release is using. (The next one is LLVM-based and is all native).

I would recommend using a toolchain that's already available (and kept up to date) via a web interface/IDE, like TI-Planet's [Project Builder](https://tiplanet.org/pb).

**Comment by Overload02** [comment]
when the toolchain becomes LLVM-based will this allow Chromebook Linux beta users to the toolchain them?

> Since you can't really do whatever you want on chromebooks unless you "root" them, it's not happening.

this is only if you want to change your OS or root android. other than that you can unable Linux in the setting of Chromebook. if its version 80 or above.

**Comment by erentar** [comment]
Well, if you get the plain sideloaded linux it should be able to run anything linux - including CEdev
