### ISSUE TITLE
gnome-calculator opens every time I try to compile my code???!!??

### ISSUE THREAD

**Issue by nathanfarlow** [CE-Programming/toolchain#285]
Here is a video of the exploit in action: https://www.youtube.com/watch?v=PYc56b5TdtA

In all seriousness, this might have serious implications for Source Coder 3, which (presumably) uses the vulnerable compiler to compile code. I predict the compiler can also be exploited on Windows but would require a more creative approach.

Can't wait for the LLVM release!
[exploit_demo.zip](https://github.com/CE-Programming/toolchain/files/5394755/exploit_demo.zip)

**Comment by mateoconlechuga** [comment]
lol

**Comment by adriweb** [comment]
lol zds indeed

**Comment by tari** [comment]
The compiler behind SourceCoder is pretty heavily sandboxed, so I think the worst you could do is exfiltrate code from other users when it gets built.

**Comment by adriweb** [comment]
> the worst you could do is exfiltrate code from other users when it gets built.
> 
Well I don't know if SC has public and private projects but since the TI-Planet's PB does, it was definitely something that was a target (@commandblockguy managed to make a PoC by including other files from .asm files since fasmg has include/file loading directives). I've since isolated things even more in PB projects and there isn't any such "cross"-including / LFI issues anymore as far as I know (except for what would be in the toolchain itself, which is, well, expected to be possible). So anyway, if there are private projects/data, you might want to look into it on your side as well?

**Comment by mateoconlechuga** [comment]
the latest push to master makes this a thing of the past :)
