### ISSUE TITLE
Number input

### ISSUE THREAD

**Issue by milanovitch44** [CE-Programming/toolchain#286]
I can't find a way to input numbers in C. Do you know if there is a function for this?

If not I could make a function, but I just wanted to make sure there isn't one already.
- If I make the function, should I give an error when the number is to big, or should I just round the number (would go automatically)?
- If I make the function, can I make it in C?

**Comment by adriweb** [comment]
Sure there is, see https://github.com/CE-Programming/toolchain/tree/master/examples/standalone/os_input for instance. But it's not necessarily the only way. Especially since there could be custom input routines easily doable depending on the context (if using graphx+keypadc etc). There are various programs that do that. Fortunately almost everything in the CE community is open source, giving everyone an opportunity to learn more easily.

**Comment by milanovitch44** [comment]
Thank your very much!
