### ISSUE TITLE
Add a way to determine function size

### ISSUE THREAD

**Issue by epsilonfive** [CE-Programming/toolchain#295]
A new feature that would be helpful when optimizing programs for size, it would just need to output the names of each function and their respective sizes in bytes. The current .map file generated when using the OUTPUT_MAP makefile option only outputs addresses, which isn't very useful, since they aren't sorted. This could be either done by improving the OUTPUT_MAP option, or by adding a whole new one, OUTPUT_FUNCTION_INFO or similar.

**Comment by jacobly0** [comment]
This isn't currently possible in release mode, and debug mode already outputs this information in the debugging info.  If you really are willing to use incorrect information like address differences, then it's easy enough to compute from the map file yourself, but it can't be an official feature since it would be incorrect information.
