### ISSUE TITLE
How to deal with special chars (accents maths symbols etc...) with fontlib

### ISSUE THREAD

**Issue by MathisTLD** [CE-Programming/toolchain#306]
Hi, i wanted to create a small program that stores notes with menus etc but displaying text in french is a bit tricky as I can't get accents to work properly
I also wonder if it's possible to use maths symbols etc ...
Thanks for your help

**Comment by drdnar** [comment]
Are you trying to use the OS text routines? The OS uses a totally different character mapping than Unicode or Windows 1252.

GraphX's built-in font only supports basic ASCII; it doesn't have any accented characters at all. However, my [my sample fonts](https://github.com/drdnar/ce-fonts/releases) for use with [the FontLibC library](https://ce-programming.github.io/toolchain/libraries/fontlibc.html) fully support French (as well as most other common Latin-based scripts), and you can freely distribute them with your program. The "Calc-1252" character set used in Dr. Sans is largely based on the popular Windows 1252 set, which is used in the other fonts, so if you can force your code editor to Windows 1252, French accents should just work without trouble. I also wrote [a header file](https://github.com/drdnar/progcalc/blob/master/src/calc1252.h) that has includes for all of the special symbols _except_ for the accented ones. C combines string sequential literals, e.g. `prinf("asdf" "jkl");` is exactly the same as `printf("asdfjkl");`, so with that header you can do something like `fontlib_DrawString(CALC1252_pi "is about 3.14159265.");` to show the text "π is about 3.14159265."

If you really have a burning desire for it, I can adapt the other fonts in that set to have the same extended character set as Dr. Sans. I spent a fair bit of time adding a full set of accents to the Dr. Sans family, so it'd be nice to see someone use them for once!

**Comment by MathisTLD** [comment]
Thanks so much for your reply !
I'm using fontlib with the "test-font" provided in the example so I will switch to your Dr. Sans
I was using utf8 strings in code I generate with JS script that reads .txt files so I assume I have to convert these into  Windows 1252 to have proper chars displayed on screed right ?
By reading your header file I see that it contains charcodes for barely every char I need (I think only ∂ is missing but I can totally go without it). I will try to fix my program by following your guidelines. Il Tell you if it works
Thanks for everything

**Comment by drdnar** [comment]
Actually the test fonts in the examples are older versions of Dr. Sans. However, using UTF-8 will definitely just show garbage for anything other than basic ASCII characters; FontLibC only supports 8-bit character sets for optimal performance. You'll have to convert your strings to Windows 1252. However, Dr. Sans isn't strictly Windows 1252: there are a handful of characters changed and some added, so for those differences, you'll have to use the equates. 

The following characters are removed from Windows 1252: 
- All _combining_ diacritic marks, as FontLibC does not have support for combining marks: 
  - Circumflex ˆ 
  - Tilde ˜ (regular tilde ~ is still there)
  - Diaeresis ¨
  - Macron ¯
  - Acute accent ´
  - Cedilla ¸
- ƒ, because the florin is either rare or obsolete
- Ellipsis … because it's unnecessary
- ¥, because Japanese and Chinese aren't supported, so why bother?
- Broken bar ¦, because it's mostly pointless
- ™ © ®, because modern intellectual property law needs serious reform
- Soft hyphen (code point 0xAD), because you would need to implement that as a control code

The following additions have been made:
- A bunch of cursor characters
  - Codepoint 0 is the same width as other cursors, so it's a blank cursor in case your user interface needs that
- ▴ ▾ ◄ ► are also intended for cursors, specifically for pointing to things
- Some arrows ↑ ↓ ← →
- ↔, which did not display as an emoji in 1981
- ○ • for use in GUIs as either checkboxes or radio buttons
- Various math symbols: 
  - Integral ∫
  - There exists ∃
  - For all ∀
  - Therefore ∴
  - Root √
  - Inequality ≤ ≥ ≠ 
  - Approximately equal ≈
  - Infinity ∞
- Various Greek characters: α Γ γ Δ δ ε η θ Λ λ µ ξ Π π Σ σ φ Ω ω 
- You can do what everyone did in the 80s and pretend German [ß (ss ligature)](https://en.wikipedia.org/wiki/%C3%9F) is actually Greek beta β
- 0xAD `CALC1252_MINUS` − is the subtraction symbol, which is the same width as +, unlike 0x2D hypen-minus -

**Comment by drdnar** [comment]
It seems I should add a comment about character encoding to the FontLibC documentation. It also sounds like your question has been answered, so I'll close this issue.
