### ISSUE TITLE
Error: symbol ':globals.__ftoul' is undefined or out of scope.

### ISSUE THREAD

**Issue by tarneaux** [CE-Programming/toolchain#370]
I'm using the srldrvce/srl_echo example.
`make` outputs:
```
[compiling] src/main.c
[convimg] icon.png
[linking] bin/DEMO.bin
/home/max/CEdev/meta/ld.alm [1488] macro ? [1235] :read? [7] /home/max/CEdev/meta/../lib/shared/printf.c.src [3374]:
	extern __ftoul
extern? [12] (CALM)
Error: symbol ':globals.__ftoul' is undefined or out of scope.
make: *** [/home/max/CEdev/meta/makefile.mk:228: bin/DEMO.bin] Error 2
```

(Using [this build](https://jacobly.com/artifact?repo=toolchain&branch=srldrvce-rewrite&file=CEdev-Linux))

**Comment by commandblockguy** [comment]
Looks like the compiler version in that release expected some routines that were recently added and not yet included in the srldrvce-rewrite branch, so I went ahead and rebased the branch so that it would include those. Give it a few minutes for the build to complete and then try installing the toolchain again from the same link.
