### ISSUE TITLE
No C++ Standard Library???

### ISSUE THREAD

**Issue by TheMiningTeamYT** [CE-Programming/toolchain#442]
I'm trying to compile a C++ program I wrote for my TI 84+ CE Python Edition calculator using this tool chain. However, when I ran a test compile while trying to write a makefile I was informed that "'string' file not found". Upon closer inspection, as in reading through other github issues, I realized that the entire C++ standard library is absent. Why is this the case? Are there any plans to add the C++ standard library in the future? And where can I find a substitute?
(for reference, I need something that provides `<string>`, `<map>`, and `<regex>`)

**Comment by adriweb** [comment]
It is indeed absent from the toolchain, and while we have briefly discussed
choosing a small one, for now we haven't done so, so it's up to you to
choose one that compiles and works (for you, and for the CE...), possibly
by removing parts that you aren't using so that it takes the minimum amount
of space possible. This is in fact a major issue because the memory is
quite small on the device, and you probably won't be able to easily port
any project that isn't sufficiently small. Use C (or STL-less C++) if you
can...
