### ISSUE TITLE
boot_SetTime not working on actual hardware.

### ISSUE THREAD

**Issue by lightcreations** [CE-Programming/toolchain#492]
boot_SetTime seems to work inside of CEmu using the ROM dump of my calculator but has no function on actual hardware.

```c
#include <sys/rtc.h>

int main() {
    boot_SetDate(2, 3, 2020); // works
    boot_SetTime(30, 30, 12); // doesn't work on hardware

    return 0;
}
```

Rev W
Boot code: 5.3.6.0017
OS version: 5.4.0.0034

**Comment by calc84maniac** [comment]
It turns out that this is due to a bug in `boot_SetTime()` which doesn't properly wait until the previous RTC load operation is completed before attempting to start a new one, meaning the second load operation never takes place. However, it does wait until the previous time registers are loaded into the RTC before writing them, which means the values from the previous load in `boot_SetDate()` are the ones that end up in the RTC.

A workaround for this issue would be to call `boot_SetDate()` (which doesn't have this bug) after `boot_SetTime()`, or if it's possible that an RTC load may be in progress for any other reason, you could loop `while (rtc_IsBusy());` before calling `boot_SetTime()`.

Leaving this issue open until toolchain documentation is updated.
