### ISSUE TITLE
Integrate fasmg into toolchain build process and program linking

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/toolchain#82]
This should build the shared libraries and link user programs. Convhex can stick around for compression uses I guess.

**Comment by debrouxl** [comment]
The source code of fasmg doesn't seem to be available, and no binary is provided for MacOS X...
While I definitely like the idea of a generic macro-assembler, are we sure we want to tie this development environment to another piece of proprietary software (replacing some of the proprietary software from the ZDS stack, but still) ?
Projects packaged by a variety of Linux distros, such as libticalcs, will have to keep depending on portable, open source (if otherwise imperfect) software such as spasm.

**Comment by adriweb** [comment]
I'm not sure if anyone has ever asked about a macOS port/version to the author, or at least the source to take care of that ourselves, so it's worth a try...
And technically, due to the nature of fasmg, it's actually possible (though cumbersome) to "convert" the linux elf binary into a macOS mach-o one and have it still work, @jacobly0 had me test such a version at some point, although I don't remember if it was completely done.

In any case, using fasmg instead of the ZDS assembler won't be better on the open-sourceness side, but at least it will bring linux users of the CE toolchain one step closer to using native tools only instead of using wine.

**Comment by mateoconlechuga** [comment]
The source of fasmg is included right in the download? I'm not sure what you mean.

**Comment by adriweb** [comment]
Uhhh yes it is, I just checked. I could swear it wasn't there at some point.
Glad to see we'll be able to work on that :)

**Comment by debrouxl** [comment]
After Adriweb's message, I failed to find a pure source code distributil, as provided by most projects, and failed to read the "Open source assembly language compiler." subtitle on the page.  Sorry for the noise :)

**Comment by mateoconlechuga** [comment]
Currently in progress; really the only thing left is to add proper support in the linker for handling library asm files.

**Comment by mateoconlechuga** [comment]
Has now been merged into master, and appears to be working! :D
